name: YoutubeBurgundy
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.11.14
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiofiles==25.1.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - blinker==1.9.0
      - click==8.3.1
      - colorama==0.4.6
      - fastapi==0.124.0
      - flask==3.1.2
      - h11==0.16.0
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mutagen==1.47.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-multipart==0.0.20
      - starlette==0.50.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uvicorn==0.38.0
      - werkzeug==3.1.4
      - yt-dlp==2025.11.12
